### ISSUE TITLE
Error en pagina cuando das en Adopción

### ISSUE THREAD

**Issue by vetlog** [josdem/vetlog-spring-boot#164]
**Todo**

Al momento de dar en adopción, el candidato no aparece en el listado, así mismo no se visualiza la descripción de cada perrito

**Comment by josdem** [comment]
- User should go to the: "ARE YOU READY TO SELECT A NEW MEMBER OF YOUR FAMILY? section
- Please see how a pet is listed here for adoption: https://vetlog.org/pet/listForAdoption
