### ISSUE TITLE
Update Spring Boot to the latest version

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#201]
As a **user**, I want to update vetlog to the latest version `3.1.2` **so that** I can have the latest version

**Acceptance Criteria**
- I am able to see the latest version on `build.gradle` file
- I am able to run test cases
- I am able to run the application

**Comment by trustbycode** [comment]
Hey @josdem  the following dependencies are updated

Spring Boot
Thymeleaf Security5
Mockito


awsLambdaVersion = '1.1.0'
awsJavaVersion = '1.11.98'

Needs an update if you're migrating to Java v2
