### ISSUE TITLE
Take a look at the next milestone

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#218]
Hi contributors, this issue is to thank you for your previous contributions to Vetlog, and let you know about the new cool features we want to deliver; please take a look at them when you have a chance:

### Milestone
https://github.com/josdem/vetlog-spring-boot/milestone/1

### Issues
https://github.com/josdem/vetlog-spring-boot/issues

Thanks again! 🐕❤️

**Comment by sindhunaydu** [comment]
Hi @josdem, thanks and it was really fun to work on those issues. I'm currently on vacation, I'll take a look at the new and cool features as soon as I'm back. 🎉🎉

**Comment by josdem** [comment]
> Hi @josdem, thanks and it was really fun to work on those issues. I'm currently on vacation, I'll take a look at the new and cool features as soon as I'm back. 🎉🎉

Sounds good, enjoy your time off! 😀

**Comment by marki2121** [comment]
Hi @josdem i am thrilled to work on the new issues

**Comment by josdem** [comment]
> Hi @josdem i am thrilled to work on the new issues

I am glad, your contribution is appreciated.
