### ISSUE TITLE
Update font family

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#219]
As **a user**, I want to update the font family link **so that** I can avoid a request blocked with the old format

**Acceptance Criteria**
- I am able to see a new font link in the `head` HTML section
- I do not see the following error on the home page:

`Mixed Content: The page at 'https://vetlog.org/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Montserrat:400,700'. This request has been blocked; the content must be served over HTTPS.`

**References**
- https://fonts.google.com/specimen/Varela+Round?query=Varela

**Comment by Shubh8899** [comment]
I would like to work on this one.

**Comment by josdem** [comment]
> I would like to work on this one.

Thanks @Shubh8899 your collaboration is appreciated. Let me know if you have any questions.

**Comment by josdem** [comment]
Deployed to prod: https://ci.josdem.io/job/vetlog-pipeline/24/
