### ISSUE TITLE
Fixing grammar in home page

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#233]
As **a user**, I want to fix some grammar on the home page **so that** I can use English sentences correctly

**Acceptance Criteria**
- I can see accurate grammar on the home page: https://vetlog.org/

**Comment by uhdf823f** [comment]
Hello, I've found several grammar errors on the homepage. May I submit them?

**Comment by uhdf823f** [comment]
Hello, I've found several grammar errors on the homepage. May I commit?

**Comment by josdem** [comment]
I created a hotfix to incorporate @uhdf823f  changes in production: https://ci.josdem.io/job/vetlog-pipeline/26/
Deployed version: `1.5.1` https://vetlog.org/actuator/info
