### ISSUE TITLE
Carousel arrow control is not working fine

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#236]
**Steps to reproduce**
- Go to the list pet for adoption section: https://vetlog.org/pet/listForAdoption
- Click in an arrow image control except the first one

**Expected result**
- Carousel rotates in the direction I selected

**Actual result**
- First pet image responds to the rotation control

**References**
https://getbootstrap.com/docs/4.0/layout/grid/

**Comment by Shubh8899** [comment]
i would like to work on this

**Comment by josdem** [comment]
It is assigned to you; I appreciate your collaboration.

**Comment by josdem** [comment]
Deployed to production: https://ci.josdem.io/job/vetlog-pipeline/36/
Current version: `1.6.0` : https://vetlog.org/actuator/info
