### ISSUE TITLE
Run tests automatically on PR

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#238]
As **repository admin**, I would like to trigger Jenkins build when a developer sends a PR **so that* I can provide feedback about changes.

**Acceptance Criteria**
- I can see a Jenkins job is triggered after a PR: https://ci.josdem.io/job/vetlog/

**References**
https://www.cloudbees.com/blog/better-integration-between-jenkins-and-github-github-jenkins-plugin

**Comment by marki2121** [comment]
I will look into this later today, but i am not making any promises. 👌

**Comment by marki2121** [comment]
I just took a quick glance at the doc and i will not be able to do this because of admin permissions.

**Comment by josdem** [comment]
Finally! I got a build on a PR: `34762240-7853-11ee-88f4-c8d607c8d37e pull_request.open`
Jenkins build: https://ci.josdem.io/job/vetlog/58/
No code changes were required.
