### ISSUE TITLE
Register your pet records is not going to the right page

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#239]
**Steps to reproduce**
- Click on: "DO IT NOW!" button at the home page
- Enter a valid user's credentials

**Expected behavior**
- I can see my pet lists so that I can select the one to see the Vet logs

**Actual result**
- User goes to an invalid page: https://vetlog.org/petlog/create

**Comment by josdem** [comment]
Deployed to production: https://ci.josdem.io/job/vetlog-pipeline/29/

**Comment by SinyukKirill** [comment]
oh, sorry, just noticed your fix. Haven't read the problem carefully :C

**Comment by josdem** [comment]
No worries, I appreciate your help.
