### ISSUE TITLE
Wrong birthDate if date is before 2000

### ISSUE THREAD

**Issue by SinyukKirill** [josdem/vetlog-spring-boot#248]
During exploring pages found an unexpected behaviour.

**Steps to reproduce:**
 1) Create a pet with birthDate with year before 2000(e.g. 1999)
 2) Pet card will show birth year 2099
 
 The problem is in several date conversions from localDateTime to String and back again. Date in DB is correct.

**Comment by SinyukKirill** [comment]
it seems unlikely to have a pet older than 23y.o. but who knows...
I also can fix it

**Comment by josdem** [comment]
Hi @SinyukKirill thanks for pointing out this issue, I went ahead and created a PR from your changes. Your collaboration is appreciated.

**Comment by josdem** [comment]
This ticket depends on this one: https://github.com/josdem/vetlog-spring-boot/issues/253
