### ISSUE TITLE
Display pet birthday based on user's locale configuration

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#253]
As **a user**, I want to display the pet's birthday based on the user's locale format **so that** I can display information based on the user's language

**Acceptance Criteria**

- The User is able to see the pet's birthday in Spanish format
- The user is able to see the pet's birthday in English format

**Notes** 
- Format depends on user's locale configuration
- Supported languages are Spanish and English

References:
https://stackoverflow.com/questions/40833933/thymeleaf-get-current-locale

**Comment by SinyukKirill** [comment]
can assign it on me

**Comment by josdem** [comment]
It is assigned to you; thanks for the help!

**Comment by josdem** [comment]
Deployed to production: https://ci.josdem.io/job/vetlog-pipeline/31/
Current version: `1.5.5` https://vetlog.org/actuator/info
