### ISSUE TITLE
Update Apache license

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#266]
As **a user**, I want to update the Apache license **so that** I can have it up to date

**Acceptance Criteria**
- I can see an update from 2023 to 2024
- I can see an update from `joseluis.delacruz@gmail` to `contact@josdem.io`

**Comment by pojith** [comment]
can i solve

**Comment by josdem** [comment]
> can i solve

Absolutely, your help is much appreciated. I assigned this ticket to you; let me know if you have any questions.

**Comment by pojith** [comment]
can u check now
