### ISSUE TITLE
Image carousel not working in admin's pet list

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#303]
**Steps to reproduce**
- Login as admin user
- Search for any user with two or more pets registered
- Click on right or left carousel arrows

**Expected result**
- Pet image rotates in clicked arrow 

**Actual result**
- First pet on the list is rotating instead

**Comment by yashudhlani** [comment]
Hi @josdem , sorry but can you tell me if I am looking at the right screen here - 
I cannot find the carousel. I have logged in as a admin in local, and search user josdem who has 4 pets but I don't see any carousel

<img width="1250" alt="image" src="https://github.com/user-attachments/assets/759cb203-3ac8-4a2c-bfc4-021644483f6f">

**Comment by josdem** [comment]
> Hi @josdem , sorry but can you tell me if I am looking at the right screen here - I cannot find the carousel. I have logged in as a admin in local, and search user josdem who has 4 pets but I don't see any carousel
> 
> <img alt="image" width="1250" src="https://private-user-images.githubusercontent.com/44999427/365668432-759cb203-3ac8-4a2c-bfc4-021644483f6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MDczMTYsIm5iZiI6MTcyNTkwNzAxNiwicGF0aCI6Ii80NDk5OTQyNy8zNjU2Njg0MzItNzU5Y2IyMDMtM2FjOC00YTJjLWJmYzQtMDIxNjQ0NDgzZjZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE4MzY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZDcxMTliZDRjM2QwNWQ1OTEyY2UzOGMwMmU0ZjMwMWE1ZWEwZjdhMmQ4YTY3Y2IxNWE0MTk1ODIwYzgyZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9IJggq4zY4YfwbAmM7vgxi70KlixE02L2_fvNSVkUEc">

Hi @yashudhlani , this is a edge scenario, in order to help you to reproduce it, I created a dump SQL file wich you can import in your local environment to reproduce the issue.

**Instructions:**
- Login using admin: username: `admin`  password: `12345678`
- Search for user `josdem`
- You will find two pets
  - Cremita
  - Kranky
-  Click on right Kranky's pet image arrow
- You will see how rotates Cremita's image instead. 

[vetlog-test-issue-303.txt](https://github.com/user-attachments/files/16935131/vetlog-test-issue-303.txt)

**Comment by yashudhlani** [comment]
@josdem any changes made to the html files are not reflecting on restarting the service. Any suggestion how to make it reflect on the browser?

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/328
