### ISSUE TITLE
Create vaccination model

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#304]
As a **user**, I want to create a vaccination model **so that** I can register next vaccination for my pet.

**Acceptance Criteria**
- I have a vaccination model with these fields
  - name (Vaccination name)
  - date (MM/dd/YYYY format)
  - status (PENDING, APPLIED)

**References**
- https://github.com/josdem/vetlog-spring-boot/wiki/Vaccination-Program

**Comment by kaminuma** [comment]
Hi
Wanting to contribute for the first time, 
I set up a local environment. 
For this issue, should I create a model file with the above items in the model directory in MVC?
If the recognition is correct, please assign it.

**Comment by josdem** [comment]
> Hi Wanting to contribute for the first time, I set up a local environment. For this issue, should I create a model file with the above items in the model directory in MVC? If the recognition is correct, please assign it.

Hi @kaminuma your understanding regarding this issue/task is correct; I assigned this issue/task to you. Please notice you can get vaccine names from the vaccionation program link. Your colaboration is appreciated!.

**Comment by kaminuma** [comment]
thanks
I got it
First, let's go as far as cutting a branch `feature/304` and issuing a PR.

**Comment by kaminuma** [comment]
@josdem 
I checked the collaborators and pushed.
Please check PR

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/310
