### ISSUE TITLE
Create next vaccines for a pet based on its birthdate

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#305]
As a **user**, I want to create next vaccination records for my pet based on its birthdate **so that** I can schedule next vaccination days.

**Acceptance Critera**
- When I register a new pet I should create all records for vaccination based on its bithdate
- All records created should follow the [Vaccination Program](https://github.com/josdem/vetlog-spring-boot/wiki/Vaccination-Program)
- All records should have the status `PENDING`

**Notes**
- This task will cover only dog pets 

**Dependencies**
- [x] [Create vaccination model](https://github.com/josdem/vetlog-spring-boot/issues/304)

**Comment by M-Aadhi** [comment]
shall i can do u it

**Comment by josdem** [comment]
> shall i can do  it 

Hi @M-Aadhi absolutely, your collaboration is appreciated. Let me know if you have any questions

**Comment by M-Aadhi** [comment]
> > shall i can do  it 
> 
> Hi @M-Aadhi absolutely, your collaboration is appreciated. Let me know if you have any questions 

It was first open source project i donno wht to do like am I have fork it r can push directly
I donno can u help me a little..plzz

**Comment by josdem** [comment]
Hi @M-Aadhi  I sent you a collaboration invitation to make the things easier. You should create a branch from `main` following naming conventions I suggest: `feature/305`. Then you can commit your changes in that branch so that you can do a PR. here is more information how to do it. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by M-Aadhi** [comment]
> Hi @M-Aadhi  I sent you a collaboration invitation to make the things easier. You should create a branch from `main` following naming conventions I suggest: `feature/305`. Then you can commit your changes in that branch so that you can do a PR. here is more information how to do it. https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Thx I will do my best

**Comment by josdem** [comment]
Hi @M-Aadhi  We normally do a PR with implementation changes based on acceptance criteria before we close an issue. Let me know if you have any questions.

**Comment by M-Aadhi** [comment]
kk sry mb

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/340
