### ISSUE TITLE
Add vaccination plan to the pet's list view

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#306]
As a **user**, I want to add all planned vaccination records to the pet's list view **so that** I can see next vaccination records and status.

**Acceptance Criteria**
- I can see the vaccination records as a table 

**Example**

| Vaccine    | Status |
| -------- | ------- |
| Parvovirus   | Pending   |
| Deworming  | Pending   |

**Dependencies**
- [x] [Create next vaccines for a pet based on its birthdate](https://github.com/josdem/vetlog-spring-boot/issues/305)

**References**
![amigo](https://github.com/user-attachments/assets/878065ba-3c55-43c5-a7df-3d4f97842643)

**Comment by yashudhlani** [comment]
Hi @josdem , shall I pick it up ?

**Comment by josdem** [comment]
> Hi @josdem , shall I pick it up ?

Hi @yashudhlani , absolutely, your collaboration is appreciated, let me know if you have any questions.

**Comment by josdem** [comment]
@yashudhlani  for this issue you might need to create a method in `VaccinationRepository` so that you can get all vaccinations given a pet, something like:

`List<Vaccination> findAllByPet(Pet pet);`

And Spring JPA will do the magic.

**Comment by yashudhlani** [comment]
Hi @josdem , how should we go about it ?
should I fetch the list of vaccines in the "/list" call itself, or should we do it on a button click or something?

if We are doing it on the "/list" call, I suggest we build a new DTO class to make a pet object with Vaccines being a list field and add that to the modeAndView ?

any other suggestions would also help!

**Comment by josdem** [comment]
Hi, I will do my best to describe the steps:
- You should add a `List<Vaccination> vaccines` model to the `PetController` using `list()` method
- Inject `VaccinationService` bean into the controller
- Add a `vaccinationService.getVaccinesByPet(pet)` to the `VaccinationService`
- Add a `vaccinationRepository.findVaccinesByPet(pet)` method
- Finally, add the `<div>` structure in the `templates/pet/list.html` view to show vaccines given a pet

**Comment by yashudhlani** [comment]
Hi @josdem does this UI look fine to you ?
<img width="561" alt="image" src="https://github.com/user-attachments/assets/5b2ff113-908b-4758-845a-1d41a3cb7a23">

**Comment by josdem** [comment]
> Hi @josdem does this UI look fine to you ?
> 
> <img width="561" alt="image" src="https://github.com/user-attachments/assets/5b2ff113-908b-4758-845a-1d41a3cb7a23">
> 
> 

Hi @yashudhlani ,yes it looks good to me. Thank you.

**Comment by josdem** [comment]
Hi @yashudhlani seems like you need a little help, so I added all the controller and services logic to bring vaccines by pet, you just need to work in the `templates/pet/list.html` changes. Please take a look at the branch: https://github.com/josdem/vetlog-spring-boot/tree/feature/306 and let me know if any questions.

**Comment by yashudhlani** [comment]
@josdem , do you want me to make the changes to the same branch?

**Comment by yashudhlani** [comment]
@josdem, pushed the list changes

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/341
