### ISSUE TITLE
Use var keyword when possible in service implementation

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#307]
As **developer**, I would like to use `var` keyword when possible in package `com.josdem.vetlog.service.impl` **so that** I can update Java syntax .

**Acceptance Criteria**
- I am seeing `var` usage in variables whenever is possible under the package `com.josdem.vetlog.service.impl`
- I am covering the equivalent package for tests.
- All tests are passing

**Benefits of using var in Java**
- A simplified syntax for method block logic.
- A familiar syntax for JavaScript, Go, Rust and Pascal programmers.
- Easier onboarding experience for developers new to Java.
- Enhanced ease of development for methods and local blocks of code.

**When not to use var**
- `var` cannot be used in a method signature.
- `var` cannot be used to declare instance variables.
- `var` cannot be used to declare static variables.
- `var` cannot be used if a variable is initially set to null.

**Comment by kaminuma** [comment]
@josdem 
Sorry, I live in Japan and it's been late lately and I think I'm going to bed.
It hasn't been assigned to issues yet, but I've finished fixing 315, so I'll just post a PR. I apologize before being assigned.

**Comment by josdem** [comment]
> Hi @josdem I don't use var much, but I think I'll try making a PR. Can I have it assigned?
> 
> Is it okay to understand that all services will be rewritten?

Hi @kaminuma, as always, your collaboration is appreciated and welcomed.
Your understanding is correct; we want to use the `var` keyword in all service implementations whenever possible.
Basically, you can use `var` in local variables, and as soon as you understand when not to use `var` (please see issue description for more information), you should be good to go.
