### ISSUE TITLE
Improve optional validations on services

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#308]
As **developer**, I would like to handle better optional validations on services **so that** I can have a single way to solve the validations and improve code.

**Acceptance Criteria**
- Replace `isPresent()` by `isEmpty()` see:  https://github.com/josdem/vetlog-spring-boot/blob/main/src/main/java/com/josdem/vetlog/service/impl/PetServiceImpl.java#L67-L69
- Replace optional presence condition with functional style expression, see: https://github.com/josdem/vetlog-spring-boot/blob/main/src/main/java/com/josdem/vetlog/service/impl/PetServiceImpl.java#L72-L74
- Apply the same strategy in all `com.josdem.vetlog.service.impl` package
- Modify tests accordingly

**Comment by yashudhlani** [comment]
Hi @josdem, can I pick this issue ? Looking to start contributing in open source projects. 

Would appreciate the help!🙂

**Comment by josdem** [comment]
> Hi @josdem, can I pick this issue ? Looking to start contributing in open source projects.
> 
> Would appreciate the help!🙂

Hi @yashudhlani sure thing, your collaboration is appreciated! let me know if you have any questions.

**Comment by yashudhlani** [comment]
Hi @josdem I have pushed the code and raised a PR, can you review it ?
Here's the [link](https://github.com/josdem/vetlog-spring-boot/pull/324)

**Comment by josdem** [comment]
> Hi @josdem I have pushed the code and raised a PR, can you review it ? Here's the [link](https://github.com/josdem/vetlog-spring-boot/pull/324)

Absolutely, you have some comments.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/324
