### ISSUE TITLE
Unable to use Run with Gradle commands by copying and pasting

### ISSUE THREAD

**Issue by kaminuma** [josdem/vetlog-spring-boot#313]
https://github.com/josdem/vetlog-spring-boot/wiki/execution

If you copy and paste the command
```
./gradlew -Dflyway.user=${username} -Dflyway.password=${password} -Dflyway.baselineOnMigrate=true flywayMigrate -i` 
```

the command is not recognized because it contains an unnecessary [` ] at the end

It happened when I started the environment in windows environment

**Comment by josdem** [comment]
It is fixed: https://github.com/josdem/vetlog-spring-boot/wiki/Execution sorry about that.
