### ISSUE TITLE
SPIKE - Find a way to clean up the database testing generated records

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#315]
As **developer**, I would like to have a way to clean up the testing database records **so that** I can run tests in my local and avoid failures.

**Description**
- `UserControllerTest` creates a test user with username `vetlog` and email `contact@josdem.io` 
- `PetControllerTest` creates a test pet with name: `Cremita` and type `DOG`
- Due to the previous data creation if you run the tests again those tests will fail

**Acceptance Criteria**
- I clean up user and pet records generated by tests
- I am able to run tests in my local several times avoiding flackyness

**Comment by josdem** [comment]
> Hi @josdem Is it okay to rewrite it on the test file? I fixed it and the test passed without any problems.

Hi @yashudhlani Absolutely, clean up in the test file is always an option, please feel free to send your changes in a PR and we can go from there.

**Comment by kaminuma** [comment]
@josdem 
Sorry this comment is me 😅
I commented without noticing the self-assignment. Can I also submit a PR?

**Comment by kaminuma** [comment]
Hi @yashudhlani 
I'm sorry.
Since I have submitted a PR, 
is it okay if I ask for a review? maybe there is a problem
