### ISSUE TITLE
Add user's phone number to the registration form - view

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#318]
As **a user**, I want to have my phone numnber registered **so that** I can have important information in my records.

**Acceptance Criteria**
- I can see a Phone field in the user create form
- Format should be + country code and 10 phone number digits
- Phone field should be located after Lastname field and before Email field
- +52 should be pre-populated since it is the country with most of our users.

**Example**
+52 (123) 456-7890

**References**
![Screenshot 2024-09-07 080335](https://github.com/user-attachments/assets/ef8fdfc2-49ef-4224-b811-bd15ea4960e6)

**Comment by kaminuma** [comment]
Is it okay to recognize changes only in HTML for this issue?

**Comment by kaminuma** [comment]
@josdem 
I got it.
Now, let's make this issue a front-end issue and create a PR with only the HTML modified.

**Comment by kaminuma** [comment]
@josdem 
HI
I have created a pull request.
There were some matters that needed to be shared with the backend side, so I added a little explanation to the PR. Please check it when you have time.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/320
