### ISSUE TITLE
Minor fixes for Run with Gradle for "To run tests"

### ISSUE THREAD

**Issue by kaminuma** [josdem/vetlog-spring-boot#321]
now Run with Gradle To run tests ,s command is
`./gradle -Dspring.config.location=$HOME/.vetlog/application-development.yml jacocoTestReport test`

But maybe this should be missing "w"

**Acceptance Criteria**

- do with To run tests by copying and pasting

I didn't really know how to write an issue, so I'm trying to write it like a template. Please let me know if there is any problem mm

**Comment by josdem** [comment]
> now Run with Gradle To run tests ,s command is `./gradle -Dspring.config.location=$HOME/.vetlog/application-development.yml jacocoTestReport test`
> 
> But maybe this should be missing "w"
> 
> **Acceptance Criteria**
> 
> * do with To run tests by copying and pasting
> 
> I didn't really know how to write an issue, so I'm trying to write it like a template. Please let me know if there is any problem mm

No worries, you are doing it great! I just added a label as documentation. 
I fixed it, good catch!

**Comment by josdem** [comment]
@all-contributors please add @kaminuma for content

**Comment by josdem** [comment]
> now Run with Gradle To run tests ,s command is `./gradle -Dspring.config.location=$HOME/.vetlog/application-development.yml jacocoTestReport test`
> 
> But maybe this should be missing "w"
> 
> **Acceptance Criteria**
> 
> * do with To run tests by copying and pasting
> 
> I didn't really know how to write an issue, so I'm trying to write it like a template. Please let me know if there is any problem mm

Also, run commands in the wiki page are for Linux/Mac platforms, if you are using windows I suggest to use Run/debug configurations using IntelliJ, this is my `bootRun` configuration:
![Screenshot 2024-09-07 192238](https://github.com/user-attachments/assets/cd29050e-e0b5-4ec0-a634-7eab2a213d20)

**Comment by kaminuma** [comment]
Thanks for the information!
