### ISSUE TITLE
Wrong message on account created

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#332]
**Steps to reproduce**
- Go to create user account: http://localhost:8080/user/create
- Fill out all fields with valid information
- Click on submit button

**Expected result**
A mesage: Your account was created

**Actual result**
![Screenshot 2024-09-10 140838](https://github.com/user-attachments/assets/c1e63e31-f4ca-459f-b6a4-f863e6bc2722)

**Comment by Prathyusha287** [comment]
Hi @josdem  , Shall I do it?

**Comment by josdem** [comment]
> Hi @josdem , Shall I do it?

Hi @Prathyusha287  Absolutely, your collaboration is appreciated, let me know if you have any questions.

**Comment by Prathyusha287** [comment]
Hi @josdem  ,thank you for assigning.Will  start working on it.

**Comment by Prathyusha287** [comment]
Hi @josdem Can you kindly help me on setting up this project ? .Which version of java is it compatible with?

**Comment by kaminuma** [comment]
Hi @Prathyusha287 
Please check the java settings in the build.gradle file. It must have been 21. I have already closed my PC today, so please check it. I'll also mention @josdem
josdem  Please check again!

**Comment by Prathyusha287** [comment]
Hi @kaminuma 
Thanks for the reply. I figured it out later and forgot to mention it. Also any idea on which version of gradle is being used?

**Comment by josdem** [comment]
> Hi @kaminuma Thanks for the reply. I figured it out later and forgot to mention it. Also any idea on which version of gradle is being used?

Hi @Prathyusha287 you do not need to install Gradle, you can use the wrapper within the project, for more information please go here: https://github.com/josdem/vetlog-spring-boot/wiki/execution

**Comment by josdem** [comment]
@all-contributors please add @kaminuma  for question

**Comment by Prathyusha287** [comment]
Hi @josdem @kaminuma .  I have replicated the issue and solved the issue. Can any of you  guide me on what to do now ?

**Comment by kaminuma** [comment]
Hi @Prathyusha287 
You open a branch with your changes and submit a PR.
(preferably this issues number, 
for example feature/332)

At that time, include the development members as reviewers and wait for the review. Once the reviewer approves that there are no issues, you will be able to merge. 

next action❗️
pull request on the modified branch.

@josdem 
If you have any rules for development, 
please share them🙏
thanks.

**Comment by josdem** [comment]
> Hi @Prathyusha287 You open a branch with your changes and submit a PR. (preferably this issues number, for example feature/332)
> 
> At that time, include the development members as reviewers and wait for the review. Once the reviewer approves that there are no issues, you will be able to merge.
> 
> next action❗️ pull request on the modified branch.
> 
> @josdem If you have any rules for development, please share them🙏 thanks.

Hi @kaminuma , I agree with suggested steps, you described the standard process correctly.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/336
