### ISSUE TITLE
Suggestion to use docker

### ISSUE THREAD

**Issue by kaminuma** [josdem/vetlog-spring-boot#338]
This is a light suggestion, but since this project does not use a docker container for MySQL locally, it means that each developer has to prepare their own environment, and even if you consider introducing docker, which is easy to build and launch. It might be good. 
Since we haven't used it, there may be a reason why, so I'll just raise an issue as a mild suggestion.

**Comment by Wasid786** [comment]
I would like to add this feature, can you assign this issue to me?

**Comment by josdem** [comment]
I'm moving this issue to the [Suggestions wiki page](https://github.com/josdem/vetlog-spring-boot/wiki/suggestions) so we can avoid confusion, such as sending the message that this issue is ready for pick-up.
