### ISSUE TITLE
Add vaccination status to the pet's edit view

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#344]
As a **user**, I want to add all vaccination records to the pet's edit view **so that** I can see and modify next vaccination records status.

**Acceptance Criteria**
- I can see the vaccination records as a table 
- I have a drop down menu with values 
  - PENDING
  - APPLIED
 - I am able to modify vaccines statuses and date is updated with status accordingly `LocalDate.now()`
 - The table should appear instead of `Vaccinated` checkbox

**Example**

| Vaccine    | Status |
| -------- | ------- |
| Parvovirus   | Pending   |
| Deworming  | Applied  |

**Screenshot**
![vetlog_edit](https://github.com/user-attachments/assets/a25f3336-c76b-4de7-a9a3-1700db63b7bb)

**Comment by AviraLS22** [comment]
Hi @josdem ,

I wanted to let you know that I’m actively working on the issue, but I’m facing some backend problems with compilation errors. I’ll fix these soon and keep you updated.

Thanks for your patience!

Best,
Aviral Sharma

**Comment by josdem** [comment]
Hi @AviraLS22  I added some comments to your PR looking to help you to improve:
- I appreciate the effort you did in this PR
- I would like to suggest to choose some easy tasks before you can do more complex tasks
- Try front-end changes first
- Try increase tests coverage taks first
- Try update dependencies tasks first
- Ask questions when you are unsure how to proceeded 
- Most important add always more tests (addition / updates) in your PRs.

I hope this helps.

**Comment by AviraLS22** [comment]
Thank you @josdem  for your guidance and suggestions! I really appreciate your support and will follow your advice to start with simpler tasks like front-end changes and increasing test coverage. I'll also make sure to ask questions when I'm uncertain and add more tests in my future PRs. I'll continue working on this PR and improve it accordingly. Thanks again!

**Comment by josdem** [comment]
> Thank you @josdem for your guidance and suggestions! I really appreciate your support and will follow your advice to start with simpler tasks like front-end changes and increasing test coverage. I'll also make sure to ask questions when I'm uncertain and add more tests in my future PRs. I'll continue working on this PR and improve it accordingly. Thanks again!

Thank you for accepting my feedback, since it is looking for your improvement as developer.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/373
