### ISSUE TITLE
Add register a pet to the main menu

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#348]
As a **user**, I would like to have Pet registration in the main menu **so that** I can access easily to this main feature

**Acceptance Criteria**
- I am able to see Register option in the main menu
- When I click on the Register option, I should be redirect to `/pet/create` controller

**Comment by josdem** [comment]
> Hey @josdem, I'm willing to work on this enhancement, please assign me the same if that's alright, thanks!

Hello @Irfan0025 ; Absolutely, your collaboration is appreciated, let me know if any questions.

**Comment by AviraLS22** [comment]
Hi @Irfan0025 and @josdem,

I noticed this issue has already been assigned, but I'd love to contribute if any additional help is needed or if there's another part of this feature that I could assist with. Let me know if I can collaborate on this or any future enhancements.

Looking forward to working together!

**Comment by josdem** [comment]
Hi @AviraLS22 you already have two issues assigned to you:
- https://github.com/josdem/vetlog-spring-boot/issues/345
- https://github.com/josdem/vetlog-spring-boot/issues/344
They need changes before we can merge or mark as completed, you can finish those changes so that we can assign you new issues. Let me know if you need any help.

**Comment by AviraLS22** [comment]
Hi @josdem,

 I'll prioritize finishing the changes for both issues (#345 and #344)

**Comment by josdem** [comment]
> Hi @josdem,
> 
> I'll prioritize finishing the changes for both issues (#345 and #344)

Thank you, let me know if you need any help, I can start those issues and then give them back to you so you can finish them.

**Comment by Irfan0025** [comment]
Hey @josdem, I have fixed this and created a PR, please review and approve the same, thanks

https://github.com/josdem/vetlog-spring-boot/pull/368

**Comment by josdem** [comment]
> Hey @josdem, I have fixed this and created a PR, please review and approve the same, thanks
> 
> #368

Thanks, you have comments, please take a look when you have a chance.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/368
