### ISSUE TITLE
Increase coverage to 80% or more

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#360]
As **developer**, I would like to increase coverage to 80% or more **so that** I can have a better coverage percentage.

**Acceptance Criteria**
- SonarCloud is reporting 80% of  coverage or more
- I can see some new  unit or integration testing

**References**
- https://sonarcloud.io/project/overview?id=com.josdem.vetlog%3Avetlog-spring-boot

**Screenshot**
![coverage](https://github.com/user-attachments/assets/071be5ef-eed5-43b5-aefa-ed37ece97466)

**Comment by kaminuma** [comment]
hi @josdem 
In order to achieve the 5% increase target, how about adding untested tests for the controller that receives the API?
what do you think?

I will not be participating in this issue, but
(Sorry, I'm busy this weekend)
I commented on the test code!

**Comment by josdem** [comment]
> hi @josdem In order to achieve the 5% increase target, how about adding untested tests for the controller that receives the API? what do you think?
> 
> I will not be participating in this issue, but (Sorry, I'm busy this weekend) I commented on the test code!

Hi @kaminuma , yes my target package to increase coverage is controllers, since we have less than 50%. Regarding to the busy weekend no worries, comments and feedback are always welcome.

![coverage_controllers](https://github.com/user-attachments/assets/c57465d5-65e3-4f34-a94c-bde813698fdf)

**Comment by kaminuma** [comment]
@josdem 
Thank you for the image!
I am grateful to have learned about SonarCloud for the first time.
controller is the target,
I got it.

**Comment by josdem** [comment]
> @josdem Thank you for the image! I am grateful to have learned about SonarCloud for the first time. controller is the target, I got it.

I am glad you are learning something new, your collaboration is appreciated.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/362
