### ISSUE TITLE
Adopt Testcontainers for Test Execution

### ISSUE THREAD

**Issue by JoseFRH17** [josdem/vetlog-spring-boot#369]
I recommend using **Testcontainers** to improve test reliability, consistency, and scalability. Testcontainers provides lightweight, disposable Docker containers for databases, message brokers, and other services, ideal for integration and functional tests.

### **Why Adopt Testcontainers?**
1. **Consistency**: Ensures tests run the same across all environments, reducing "works on my machine" issues.
2. **Isolation**: Each test runs in a clean, isolated environment, avoiding conflicts and leftover states.
3. **Easy CI Integration**: Simplifies test setup and runs seamlessly in CI/CD pipelines.
4. **Simplified Setup**: Automatically manages services, reducing manual maintenance.
5. **Scalability**: Handles large test suites efficiently.

**Proposed Action:**
1. Investigate potential services for containerization.
2. Update test suites to use Testcontainers.
3. Integrate with CI for consistent test results.

Testcontainers will enhance test reliability and reduce maintenance overhead.

**Resources**:
- [Testcontainers Documentation](https://www.testcontainers.org/)

**Comment by josdem** [comment]
> I recommend using **Testcontainers** to improve test reliability, consistency, and scalability. Testcontainers provides lightweight, disposable Docker containers for databases, message brokers, and other services, ideal for integration and functional tests.
> 
> ### **Why Adopt Testcontainers?**
> 1. **Consistency**: Ensures tests run the same across all environments, reducing "works on my machine" issues.
> 2. **Isolation**: Each test runs in a clean, isolated environment, avoiding conflicts and leftover states.
> 3. **Easy CI Integration**: Simplifies test setup and runs seamlessly in CI/CD pipelines.
> 4. **Simplified Setup**: Automatically manages services, reducing manual maintenance.
> 5. **Scalability**: Handles large test suites efficiently.
> 
> **Proposed Action:**
> 
> 1. Investigate potential services for containerization.
> 2. Update test suites to use Testcontainers.
> 3. Integrate with CI for consistent test results.
> 
> Testcontainers will enhance test reliability and reduce maintenance overhead.
> 
> **Resources**:
> 
> * [Testcontainers Documentation](https://www.testcontainers.org/)

Hi @JoseFRH17 I appreciate your suggestion, however we will go with GitHub actions, I like the efficiency and easy configuration to run our test cases.
