### ISSUE TITLE
Admin is not able to see vaccination records

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#376]
**Preconditions**
- Have an admin valid account
- Logged into the application

**Steps to reproduce**
- Select search from the main menu
- Enter a valid user with at least one pet in the platform

**Expectations**
I see the user's pet with the vaccination records

**Actual result**
No vaccination records are shown

**Screenshots**
- User view
![list_pet_user](https://github.com/user-attachments/assets/11262bfb-26c3-442f-83b8-77596adf10dc)

- Amin user
![list_pet_admin](https://github.com/user-attachments/assets/a647c84b-6107-44d7-8e9f-909dabe4fbb3)

**Comment by kaminuma** [comment]
Hi @josdem 
Could you please assign me?

**Comment by josdem** [comment]
> Hi @josdem Could you please assign me?

Absolutely, Thank You!

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/387
