### ISSUE TITLE
List only vaccines in Pending status 

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#377]
As **a user**, I want to list only vaccines in pending status **so that** I can show only vaccines we need to apply.

**Acceptance Criteria**
- In `templates\pet\list.html` view I can see only vaccines in pending status
- In `templates\vet\list.html` view I can see only vaccines in pending status

**Screenshot**
![list_pet_user](https://github.com/user-attachments/assets/49e22eda-02b0-4b36-89bc-3fd2ced178bb)

**Comment by Irfan0025** [comment]
Hey @josdem, I can work on this, if it is alright with you, please assign me this

**Comment by josdem** [comment]
> Hey @josdem, I can work on this, if it is alright with you, please assign me this

Hi @Irfan0025 absolutely, your collaboration is appreciated. Let me know if any questions.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/389
