### ISSUE TITLE
Improve vaccines table view

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#378]
As **a user**, I want to improve vaccines table view **so that** I can show a better version of the list

**Acceptance Criteria**
- Vaccines table looks aligned
- We improve pet list vaccines view

**Proposals**
- Set table below pet image and information
- Remove border in the table

**Screenshot**
![list_pet_user](https://github.com/user-attachments/assets/0e3cb1b6-e8e9-4fa8-9bdc-2a277b215949)

**Comment by MeFaisalAnsari** [comment]
Hey @josdem can you assign this to me? I can improve the design of the table.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/385
