### ISSUE TITLE
Add Tiktok logo and link to the footer section

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#405]
As **a user**, I would like to have a TikTok icon in the footer section **so that** I can click and open the Tiktok Vetlog profile

**Acceptance Criteria**
- I have a Tiktok icon located in the footer after Instagram icon
- When I click in the Tiktok icon I can see the [Vetlog Tiktok profile](https://tiktok.com/@vetlog_care)

**Screenshot**
![footer](https://github.com/user-attachments/assets/b226e98d-f6e7-4e36-bdc5-738df3f74c8a)

**Comment by jovdim** [comment]
Hi, I’m a beginner at contributing, but I’d like to work on this issue. I can add the TikTok icon to the footer and link it to the Vetlog TikTok profile. Please let me know if I can be assigned to it.

**Thanks**!

**Comment by slusy** [comment]
Hey, I would like to work on this

**Comment by josdem** [comment]
> Hey, I would like to work on this

Hi @slusy , absolutely, your collaboration is appreciated, let me know if any questions.

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/414
