### ISSUE TITLE
Increase coverage to 93% or more

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#430]
As **developer** I would like to have 93% overall coverage or more **so that** I can increase code validation with testing

**Acceptance Criteria**
- I can see overall code coverage to 93% or more [here](https://sonarcloud.io/summary/overall?id=josdem_vetlog-spring-boot)
- All tests are passing

**Comment by Gulin7** [comment]
Hi, @josdem , can I take this?

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/453
