### ISSUE TITLE
Unify Thymeleaf template messages

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#431]
As **user** I want to see the same alert message in all templates **so that** I can be consistent in style

**Acceptance Criteria**
- I can see [this message style](https://github.com/josdem/vetlog-spring-boot/blob/2eacc6dbe0819cc74772deec052046764f47b074/src/main/resources/templates/pet/list.html#L27L29) in all templates 
- I can see all styles like [this](https://github.com/josdem/vetlog-spring-boot/blob/2eacc6dbe0819cc74772deec052046764f47b074/src/main/resources/templates/home/home.html#L17L19) are changed to the previous bullet point style

**Comment by iishitahere** [comment]
Hi @josdem ! I'd like to work on this issue. Could you clarify the specific goals for unifying the Thymeleaf template messages? For instance, should we focus on consistency in message formats, centralizing message definitions, or something else? I'd be happy to get started once assigned!

**Comment by josdem** [comment]
> Hi @josdem ! I'd like to work on this issue. Could you clarify the specific goals for unifying the Thymeleaf template messages? For instance, should we focus on consistency in message formats, centralizing message definitions, or something else? I'd be happy to get started once assigned!

Hi @iishitahere  yes, we want to keep consitency in all message formats, it is expected to have them centralizing (aligned to the center). Basically we want to avoid this message formats:

```html
<div align="center" class="bg-warning">
     <p style="color:blue;font-size:18px;" th:text="${message}"/>
 </div>
```

And use this format instead:

```html
<div th:data-testid="petListMessage" th:if="${message}" class="alert alert-success" th:text="${message}"/>
```

If you want to know more about Thylemeaf alert messages please go here: https://getbootstrap.com/docs/4.0/components/alerts/

**Comment by iishitahere** [comment]
> > Hi @josdem ! I'd like to work on this issue. Could you clarify the specific goals for unifying the Thymeleaf template messages? For instance, should we focus on consistency in message formats, centralizing message definitions, or something else? I'd be happy to get started once assigned!
> 
> Hi @iishitahere yes, we want to keep consitency in all message formats, it is expected to have them centralizing (aligned to the center). Basically we want to avoid these message formats:
> 
> ```
> <div align="center" class="bg-warning">
>      <p style="color:blue;font-size:18px;" th:text="${message}"/>
>  </div>
> ```
> 
> And use this format instead:
> 
> ```
> <div th:data-testid="petListMessage" th:if="${message}" class="alert alert-success" th:text="${message}"/>
> ```
> 
> If you want to know more about Thymeleaf alert messages please go here: https://getbootstrap.com/docs/4.0/components/alerts/

Hi @josdem, thanks for the clarification! I understand that the goal is to centralize and standardize the message formats, avoiding inline styles and ensuring consistency by using the specified alert format. I'll get started on this and keep you updated on my progress. Let me know if there's anything else you'd like me to consider while working on this.

**Comment by iishitahere** [comment]
Hi @josdem ,

I've completed the changes to unify the Thymeleaf template messages, as outlined in the issue. The error page has been refactored to use a consistent Bootstrap alert format for message display.

The PR is ready for review: https://github.com/josdem/vetlog-spring-boot/pull/443

Please let me know if you have any feedback or if further adjustments are needed.

Thanks!

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/448
