### ISSUE TITLE
Add delete pet functionality to the admin user

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#433]
As **admin user** I want to have the delete pet functionality **so that** I can delete a pet from a specific user

**Acceptance Criteria**
- I can see delete button in template [vet list](https://github.com/josdem/vetlog-spring-boot/blob/main/src/main/resources/templates/vet/list.html)
- As admin when I click on delete button and in delete confirmation modal then the pet should be deleted from the platform
- As admin I can not delete a pet if it is in adoption status

**Comment by Popokok** [comment]
Hi, I would like to contribute to your project. Would you assign this issue to me please?
