### ISSUE TITLE
Unable to register a pet without time only Firefox

### ISSUE THREAD

**Issue by josdem** [josdem/vetlog-spring-boot#445]
**Steps to reproduce**
- Open a Firefox browser
- Go to register [a pet link](https://vetlog.org/pet/create)
- Fill all data from the form
- Click on Submit button

**Expectation**
A new pet is registered

**Actual result**
- Invalid birthdate due to missing time 

**Screenshot**
![vetlog_invalid_birthdate](https://github.com/user-attachments/assets/80c70611-221f-4887-b883-6252159a116f)

**Comment by krooldonutz** [comment]
Hello, can you assign me to this. I may have a solution for this. and this issue happens in safari and chrome too btw

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/vetlog-spring-boot/pull/447
